# Generated by Django 3.2.9 on 2022-05-28 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='comentario',
        ),
    ]
